### ISSUE TITLE
No more Letter in response boxes (question sheet)

### ISSUE THREAD

**Issue by lauhub** [maelvalais/homebrew-amc#9] opened 2018-03-30 08:45 UTC
Between 9 of march and 29 of march I noticed an annoying change: letters in question sheet are no more displayed on each answer checkbox

![pbamc](https://user-images.githubusercontent.com/3216214/38131355-0b418a5e-3407-11e8-827f-78946f738f80.png)

Same sources ran on Ubuntu gives:
<img width="410" alt="okamc" src="https://user-images.githubusercontent.com/3216214/38131419-583ae724-3407-11e8-8ca1-ec11b2b9f945.png">

Here is a working example of this (let me know if you miss some dependencies):

https://www.dropbox.com/s/vx7x6hok4t32i9o/EssaiAMC.zip?dl=0

**Comment by maelvalais** [comment] 2018-03-30 08:52
Thanks for the report, I’ll try to reproduce ASAP!

**Comment by maelvalais** [comment] 2018-03-30 09:12
I think `enseignementMEF.sty` is missing :)

**Comment by lauhub** [comment] 2018-03-30 09:15
@maelvalais Updated in Dropbox link

**Comment by maelvalais** [comment] 2018-03-30 09:16
Thanks!

**Comment by maelvalais** [comment] 2018-03-30 09:19
Now `evaluation.tex` 😁

**Comment by lauhub** [comment] 2018-03-30 09:30
Sorry ! I put a bunch of tex files in the zip file. Hope everything you need will be there :-)

**Comment by maelvalais** [comment] 2018-03-30 09:40
Thanks!
The only thing that might probably have changed is `automultiplechoice.sty`; could you run

    cp -L $(kpsewhich automultiplechoice.sty) .

so that you get a copy of the `automultiplechoice.sty` file. Could you zip it and send it over?

**Comment by lauhub** [comment] 2018-03-30 09:45
Updated in zip file

**Comment by maelvalais** [comment] 2018-03-30 09:48
I reproduced the bug!!! 👍

Something broke in `automultiplechoice.sty` between 1.3.0.2161 and 1.3.0.2186 (and later versions).

Here is the 1.3.0.2161 version: [automultiplechoice.sty.zip](https://github.com/maelvalais/homebrew-amc/files/1863286/automultiplechoice.sty.zip). Can you put it at the same place as `source.tex` and try again?

**Comment by lauhub** [comment] 2018-03-30 09:58
Yes, that is much better ! 👍 
Letter reappeared using the 1.3.0.2161 version
Let me know if you need to test next update :-)

**Comment by maelvalais** [comment] 2018-03-30 10:04
It looks like a bug existing in the upstream project; do you mind opening an [issue](https://project.auto-multiple-choice.net/projects/auto-multiple-choice/issues) there? The bug has been introduced somewhere in these commits (on GitLab):
![screen shot 2018-03-30 at 12 02 13](https://user-images.githubusercontent.com/2195781/38134192-44d4ba9c-3412-11e8-8e0f-b8510daddca5.png)

The culprit is probably the one that says _In separate answer sheet mode, organize answers "memory" in elements_ ([this commit](https://gitlab.com/jojo_boulix/auto-multiple-choice/commit/476a21a35df318387292dee0c9776862d1d91f7f))

**Comment by lauhub** [comment] 2018-03-30 10:11
Created [here](https://project.auto-multiple-choice.net/issues/548)

**Comment by maelvalais** [comment] 2018-03-30 10:13
Thanks so much! I’ll investigate. Sounds like a regression! 🤔

**Comment by lauhub** [comment] 2018-06-04 16:31
Hi, I still have the bug with version 1.3.0+hg2018-03-07 (Cellar/auto-multiple-choice/1.3.0.2199_1/bin/auto-multiple-choice)
Did you make an update since last time ?

**Comment by maelvalais** [comment] 2018-06-04 17:05
The 'stable' versions of Homebrew are stuck to 1.3.0.2199_1 because Homebrew refuses to use '1.4.0-beta1' as a stable version.

Fortunately, I added a 'devel' channel to the recipe so that we can still get the beta versions:

    brew install auto-multiple-choice --devel

As of today, the latest version is 1.4.0-beta2. Bear in mind that using `--devel` will make the installation **last longer** (~3 to 5 minutes) because it cannot use the bottling (precompiled) I do for 'stable' versions.

**Comment by maelvalais** [comment] 2018-06-28 11:17
Hi! Did you manage to make it work using `brew install auto-multiple-choice --devel`?

**Comment by lauhub** [comment] 2018-06-28 15:04
Hi, no because I need it in production mode. I preferred re-install an older working version

**Comment by maelvalais** [comment] 2018-10-07 09:09
Hi,
I'll close this issue for now. Feel free to re-open if anything comes up again 👍

**Closed by maelvalais** 2018-10-07 09:09 UTC
